kind = "mobile"
previewPath = "/"
title = "Schoolo"
version = "1.0.0"
id = "artifacts/schoolo"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 21288

[services.development]
run = "pnpm --filter @workspace/schoolo run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/schoolo", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/schoolo", "run", "serve" ]

[services.env]
PORT = "21288"
BASE_PATH = "/"
